version: 2

env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    binary: wt
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

universal_binaries:
  - replace: true
    hooks:
      post: uv run /Users/joescharf/.local/bin/pycodesign.py wt_pycodesign.ini -O {{ .Version }}

archives:
  - id: wt-macos-archive
    formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}

signs:
  - id: notarize-macos-zip
    cmd: sh
    args:
      - -c
      - 'xcrun notarytool submit "${artifact}" --keychain-profile SCHARFNADO_LLC --wait && touch "${signature}"'
    artifacts: archive
    ids:
      - wt-macos-archive
    signature: "${artifact}.notarized"
    output: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: joescharf
    name: wt
  ids:
    - wt-macos-archive
  extra_files:
    - glob: ./dist/wt_macos_universal.pkg
  draft: false
  prerelease: auto

homebrew_casks:
  - name: wt
    ids:
      - wt-macos-archive
    repository:
      owner: joescharf
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    skip_upload: auto
    homepage: "https://github.com/joescharf/wt"
    description: "Git worktree manager with iTerm2 integration"
