with-expecter: true
packages:
  github.com/joescharf/worktree-dev:
    config:
      recursive: true
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocks"
