// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	git "github.com/joescharf/worktree-dev/internal/git"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BranchDelete provides a mock function with given fields: branch, force
func (_m *MockClient) BranchDelete(branch string, force bool) error {
	ret := _m.Called(branch, force)

	if len(ret) == 0 {
		panic("no return value specified for BranchDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(branch, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_BranchDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BranchDelete'
type MockClient_BranchDelete_Call struct {
	*mock.Call
}

// BranchDelete is a helper method to define mock.On call
//   - branch string
//   - force bool
func (_e *MockClient_Expecter) BranchDelete(branch interface{}, force interface{}) *MockClient_BranchDelete_Call {
	return &MockClient_BranchDelete_Call{Call: _e.mock.On("BranchDelete", branch, force)}
}

func (_c *MockClient_BranchDelete_Call) Run(run func(branch string, force bool)) *MockClient_BranchDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockClient_BranchDelete_Call) Return(_a0 error) *MockClient_BranchDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_BranchDelete_Call) RunAndReturn(run func(string, bool) error) *MockClient_BranchDelete_Call {
	_c.Call.Return(run)
	return _c
}

// BranchExists provides a mock function with given fields: branch
func (_m *MockClient) BranchExists(branch string) (bool, error) {
	ret := _m.Called(branch)

	if len(ret) == 0 {
		panic("no return value specified for BranchExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(branch)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(branch)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(branch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BranchExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BranchExists'
type MockClient_BranchExists_Call struct {
	*mock.Call
}

// BranchExists is a helper method to define mock.On call
//   - branch string
func (_e *MockClient_Expecter) BranchExists(branch interface{}) *MockClient_BranchExists_Call {
	return &MockClient_BranchExists_Call{Call: _e.mock.On("BranchExists", branch)}
}

func (_c *MockClient_BranchExists_Call) Run(run func(branch string)) *MockClient_BranchExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_BranchExists_Call) Return(_a0 bool, _a1 error) *MockClient_BranchExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BranchExists_Call) RunAndReturn(run func(string) (bool, error)) *MockClient_BranchExists_Call {
	_c.Call.Return(run)
	return _c
}

// BranchList provides a mock function with no fields
func (_m *MockClient) BranchList() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BranchList")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_BranchList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BranchList'
type MockClient_BranchList_Call struct {
	*mock.Call
}

// BranchList is a helper method to define mock.On call
func (_e *MockClient_Expecter) BranchList() *MockClient_BranchList_Call {
	return &MockClient_BranchList_Call{Call: _e.mock.On("BranchList")}
}

func (_c *MockClient_BranchList_Call) Run(run func()) *MockClient_BranchList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_BranchList_Call) Return(_a0 []string, _a1 error) *MockClient_BranchList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_BranchList_Call) RunAndReturn(run func() ([]string, error)) *MockClient_BranchList_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentBranch provides a mock function with given fields: worktreePath
func (_m *MockClient) CurrentBranch(worktreePath string) (string, error) {
	ret := _m.Called(worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for CurrentBranch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(worktreePath)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(worktreePath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(worktreePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CurrentBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentBranch'
type MockClient_CurrentBranch_Call struct {
	*mock.Call
}

// CurrentBranch is a helper method to define mock.On call
//   - worktreePath string
func (_e *MockClient_Expecter) CurrentBranch(worktreePath interface{}) *MockClient_CurrentBranch_Call {
	return &MockClient_CurrentBranch_Call{Call: _e.mock.On("CurrentBranch", worktreePath)}
}

func (_c *MockClient_CurrentBranch_Call) Run(run func(worktreePath string)) *MockClient_CurrentBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_CurrentBranch_Call) Return(_a0 string, _a1 error) *MockClient_CurrentBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CurrentBranch_Call) RunAndReturn(run func(string) (string, error)) *MockClient_CurrentBranch_Call {
	_c.Call.Return(run)
	return _c
}

// HasUnpushedCommits provides a mock function with given fields: path, baseBranch
func (_m *MockClient) HasUnpushedCommits(path string, baseBranch string) (bool, error) {
	ret := _m.Called(path, baseBranch)

	if len(ret) == 0 {
		panic("no return value specified for HasUnpushedCommits")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(path, baseBranch)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(path, baseBranch)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, baseBranch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_HasUnpushedCommits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUnpushedCommits'
type MockClient_HasUnpushedCommits_Call struct {
	*mock.Call
}

// HasUnpushedCommits is a helper method to define mock.On call
//   - path string
//   - baseBranch string
func (_e *MockClient_Expecter) HasUnpushedCommits(path interface{}, baseBranch interface{}) *MockClient_HasUnpushedCommits_Call {
	return &MockClient_HasUnpushedCommits_Call{Call: _e.mock.On("HasUnpushedCommits", path, baseBranch)}
}

func (_c *MockClient_HasUnpushedCommits_Call) Run(run func(path string, baseBranch string)) *MockClient_HasUnpushedCommits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_HasUnpushedCommits_Call) Return(_a0 bool, _a1 error) *MockClient_HasUnpushedCommits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_HasUnpushedCommits_Call) RunAndReturn(run func(string, string) (bool, error)) *MockClient_HasUnpushedCommits_Call {
	_c.Call.Return(run)
	return _c
}

// IsWorktreeDirty provides a mock function with given fields: path
func (_m *MockClient) IsWorktreeDirty(path string) (bool, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsWorktreeDirty")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_IsWorktreeDirty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWorktreeDirty'
type MockClient_IsWorktreeDirty_Call struct {
	*mock.Call
}

// IsWorktreeDirty is a helper method to define mock.On call
//   - path string
func (_e *MockClient_Expecter) IsWorktreeDirty(path interface{}) *MockClient_IsWorktreeDirty_Call {
	return &MockClient_IsWorktreeDirty_Call{Call: _e.mock.On("IsWorktreeDirty", path)}
}

func (_c *MockClient_IsWorktreeDirty_Call) Run(run func(path string)) *MockClient_IsWorktreeDirty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_IsWorktreeDirty_Call) Return(_a0 bool, _a1 error) *MockClient_IsWorktreeDirty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_IsWorktreeDirty_Call) RunAndReturn(run func(string) (bool, error)) *MockClient_IsWorktreeDirty_Call {
	_c.Call.Return(run)
	return _c
}

// RepoName provides a mock function with no fields
func (_m *MockClient) RepoName() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RepoName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_RepoName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepoName'
type MockClient_RepoName_Call struct {
	*mock.Call
}

// RepoName is a helper method to define mock.On call
func (_e *MockClient_Expecter) RepoName() *MockClient_RepoName_Call {
	return &MockClient_RepoName_Call{Call: _e.mock.On("RepoName")}
}

func (_c *MockClient_RepoName_Call) Run(run func()) *MockClient_RepoName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_RepoName_Call) Return(_a0 string, _a1 error) *MockClient_RepoName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_RepoName_Call) RunAndReturn(run func() (string, error)) *MockClient_RepoName_Call {
	_c.Call.Return(run)
	return _c
}

// RepoRoot provides a mock function with no fields
func (_m *MockClient) RepoRoot() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RepoRoot")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_RepoRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepoRoot'
type MockClient_RepoRoot_Call struct {
	*mock.Call
}

// RepoRoot is a helper method to define mock.On call
func (_e *MockClient_Expecter) RepoRoot() *MockClient_RepoRoot_Call {
	return &MockClient_RepoRoot_Call{Call: _e.mock.On("RepoRoot")}
}

func (_c *MockClient_RepoRoot_Call) Run(run func()) *MockClient_RepoRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_RepoRoot_Call) Return(_a0 string, _a1 error) *MockClient_RepoRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_RepoRoot_Call) RunAndReturn(run func() (string, error)) *MockClient_RepoRoot_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveWorktree provides a mock function with given fields: input
func (_m *MockClient) ResolveWorktree(input string) (string, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ResolveWorktree")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ResolveWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveWorktree'
type MockClient_ResolveWorktree_Call struct {
	*mock.Call
}

// ResolveWorktree is a helper method to define mock.On call
//   - input string
func (_e *MockClient_Expecter) ResolveWorktree(input interface{}) *MockClient_ResolveWorktree_Call {
	return &MockClient_ResolveWorktree_Call{Call: _e.mock.On("ResolveWorktree", input)}
}

func (_c *MockClient_ResolveWorktree_Call) Run(run func(input string)) *MockClient_ResolveWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_ResolveWorktree_Call) Return(_a0 string, _a1 error) *MockClient_ResolveWorktree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ResolveWorktree_Call) RunAndReturn(run func(string) (string, error)) *MockClient_ResolveWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreeAdd provides a mock function with given fields: path, branch, base, newBranch
func (_m *MockClient) WorktreeAdd(path string, branch string, base string, newBranch bool) error {
	ret := _m.Called(path, branch, base, newBranch)

	if len(ret) == 0 {
		panic("no return value specified for WorktreeAdd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, bool) error); ok {
		r0 = rf(path, branch, base, newBranch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_WorktreeAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreeAdd'
type MockClient_WorktreeAdd_Call struct {
	*mock.Call
}

// WorktreeAdd is a helper method to define mock.On call
//   - path string
//   - branch string
//   - base string
//   - newBranch bool
func (_e *MockClient_Expecter) WorktreeAdd(path interface{}, branch interface{}, base interface{}, newBranch interface{}) *MockClient_WorktreeAdd_Call {
	return &MockClient_WorktreeAdd_Call{Call: _e.mock.On("WorktreeAdd", path, branch, base, newBranch)}
}

func (_c *MockClient_WorktreeAdd_Call) Run(run func(path string, branch string, base string, newBranch bool)) *MockClient_WorktreeAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockClient_WorktreeAdd_Call) Return(_a0 error) *MockClient_WorktreeAdd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WorktreeAdd_Call) RunAndReturn(run func(string, string, string, bool) error) *MockClient_WorktreeAdd_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreeList provides a mock function with no fields
func (_m *MockClient) WorktreeList() ([]git.WorktreeInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorktreeList")
	}

	var r0 []git.WorktreeInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]git.WorktreeInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []git.WorktreeInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]git.WorktreeInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_WorktreeList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreeList'
type MockClient_WorktreeList_Call struct {
	*mock.Call
}

// WorktreeList is a helper method to define mock.On call
func (_e *MockClient_Expecter) WorktreeList() *MockClient_WorktreeList_Call {
	return &MockClient_WorktreeList_Call{Call: _e.mock.On("WorktreeList")}
}

func (_c *MockClient_WorktreeList_Call) Run(run func()) *MockClient_WorktreeList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_WorktreeList_Call) Return(_a0 []git.WorktreeInfo, _a1 error) *MockClient_WorktreeList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_WorktreeList_Call) RunAndReturn(run func() ([]git.WorktreeInfo, error)) *MockClient_WorktreeList_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreePrune provides a mock function with no fields
func (_m *MockClient) WorktreePrune() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorktreePrune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_WorktreePrune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreePrune'
type MockClient_WorktreePrune_Call struct {
	*mock.Call
}

// WorktreePrune is a helper method to define mock.On call
func (_e *MockClient_Expecter) WorktreePrune() *MockClient_WorktreePrune_Call {
	return &MockClient_WorktreePrune_Call{Call: _e.mock.On("WorktreePrune")}
}

func (_c *MockClient_WorktreePrune_Call) Run(run func()) *MockClient_WorktreePrune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_WorktreePrune_Call) Return(_a0 error) *MockClient_WorktreePrune_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WorktreePrune_Call) RunAndReturn(run func() error) *MockClient_WorktreePrune_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreeRemove provides a mock function with given fields: path, force
func (_m *MockClient) WorktreeRemove(path string, force bool) error {
	ret := _m.Called(path, force)

	if len(ret) == 0 {
		panic("no return value specified for WorktreeRemove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(path, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_WorktreeRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreeRemove'
type MockClient_WorktreeRemove_Call struct {
	*mock.Call
}

// WorktreeRemove is a helper method to define mock.On call
//   - path string
//   - force bool
func (_e *MockClient_Expecter) WorktreeRemove(path interface{}, force interface{}) *MockClient_WorktreeRemove_Call {
	return &MockClient_WorktreeRemove_Call{Call: _e.mock.On("WorktreeRemove", path, force)}
}

func (_c *MockClient_WorktreeRemove_Call) Run(run func(path string, force bool)) *MockClient_WorktreeRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockClient_WorktreeRemove_Call) Return(_a0 error) *MockClient_WorktreeRemove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WorktreeRemove_Call) RunAndReturn(run func(string, bool) error) *MockClient_WorktreeRemove_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreesDir provides a mock function with no fields
func (_m *MockClient) WorktreesDir() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorktreesDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_WorktreesDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreesDir'
type MockClient_WorktreesDir_Call struct {
	*mock.Call
}

// WorktreesDir is a helper method to define mock.On call
func (_e *MockClient_Expecter) WorktreesDir() *MockClient_WorktreesDir_Call {
	return &MockClient_WorktreesDir_Call{Call: _e.mock.On("WorktreesDir")}
}

func (_c *MockClient_WorktreesDir_Call) Run(run func()) *MockClient_WorktreesDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_WorktreesDir_Call) Return(_a0 string, _a1 error) *MockClient_WorktreesDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_WorktreesDir_Call) RunAndReturn(run func() (string, error)) *MockClient_WorktreesDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
