// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPRCreateFunc is an autogenerated mock type for the PRCreateFunc type
type MockPRCreateFunc struct {
	mock.Mock
}

type MockPRCreateFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPRCreateFunc) EXPECT() *MockPRCreateFunc_Expecter {
	return &MockPRCreateFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: args
func (_m *MockPRCreateFunc) Execute(args []string) (string, error) {
	ret := _m.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (string, error)); ok {
		return rf(args)
	}
	if rf, ok := ret.Get(0).(func([]string) string); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPRCreateFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockPRCreateFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - args []string
func (_e *MockPRCreateFunc_Expecter) Execute(args interface{}) *MockPRCreateFunc_Execute_Call {
	return &MockPRCreateFunc_Execute_Call{Call: _e.mock.On("Execute", args)}
}

func (_c *MockPRCreateFunc_Execute_Call) Run(run func(args []string)) *MockPRCreateFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockPRCreateFunc_Execute_Call) Return(_a0 string, _a1 error) *MockPRCreateFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPRCreateFunc_Execute_Call) RunAndReturn(run func([]string) (string, error)) *MockPRCreateFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPRCreateFunc creates a new instance of MockPRCreateFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPRCreateFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPRCreateFunc {
	mock := &MockPRCreateFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
