// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSafetyCheckFunc is an autogenerated mock type for the SafetyCheckFunc type
type MockSafetyCheckFunc struct {
	mock.Mock
}

type MockSafetyCheckFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSafetyCheckFunc) EXPECT() *MockSafetyCheckFunc_Expecter {
	return &MockSafetyCheckFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: wtPath
func (_m *MockSafetyCheckFunc) Execute(wtPath string) (bool, error) {
	ret := _m.Called(wtPath)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(wtPath)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(wtPath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(wtPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSafetyCheckFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSafetyCheckFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - wtPath string
func (_e *MockSafetyCheckFunc_Expecter) Execute(wtPath interface{}) *MockSafetyCheckFunc_Execute_Call {
	return &MockSafetyCheckFunc_Execute_Call{Call: _e.mock.On("Execute", wtPath)}
}

func (_c *MockSafetyCheckFunc_Execute_Call) Run(run func(wtPath string)) *MockSafetyCheckFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSafetyCheckFunc_Execute_Call) Return(safe bool, err error) *MockSafetyCheckFunc_Execute_Call {
	_c.Call.Return(safe, err)
	return _c
}

func (_c *MockSafetyCheckFunc_Execute_Call) RunAndReturn(run func(string) (bool, error)) *MockSafetyCheckFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSafetyCheckFunc creates a new instance of MockSafetyCheckFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSafetyCheckFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSafetyCheckFunc {
	mock := &MockSafetyCheckFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
