// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockCleanupFunc is an autogenerated mock type for the CleanupFunc type
type MockCleanupFunc struct {
	mock.Mock
}

type MockCleanupFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCleanupFunc) EXPECT() *MockCleanupFunc_Expecter {
	return &MockCleanupFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: wtPath, branch
func (_m *MockCleanupFunc) Execute(wtPath string, branch string) error {
	ret := _m.Called(wtPath, branch)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(wtPath, branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCleanupFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCleanupFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - wtPath string
//   - branch string
func (_e *MockCleanupFunc_Expecter) Execute(wtPath interface{}, branch interface{}) *MockCleanupFunc_Execute_Call {
	return &MockCleanupFunc_Execute_Call{Call: _e.mock.On("Execute", wtPath, branch)}
}

func (_c *MockCleanupFunc_Execute_Call) Run(run func(wtPath string, branch string)) *MockCleanupFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCleanupFunc_Execute_Call) Return(_a0 error) *MockCleanupFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCleanupFunc_Execute_Call) RunAndReturn(run func(string, string) error) *MockCleanupFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCleanupFunc creates a new instance of MockCleanupFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleanupFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleanupFunc {
	mock := &MockCleanupFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
