// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTrustPruner is an autogenerated mock type for the TrustPruner type
type MockTrustPruner struct {
	mock.Mock
}

type MockTrustPruner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrustPruner) EXPECT() *MockTrustPruner_Expecter {
	return &MockTrustPruner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: dir
func (_m *MockTrustPruner) Execute(dir string) (int, error) {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(dir)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrustPruner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTrustPruner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - dir string
func (_e *MockTrustPruner_Expecter) Execute(dir interface{}) *MockTrustPruner_Execute_Call {
	return &MockTrustPruner_Execute_Call{Call: _e.mock.On("Execute", dir)}
}

func (_c *MockTrustPruner_Execute_Call) Run(run func(dir string)) *MockTrustPruner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTrustPruner_Execute_Call) Return(_a0 int, _a1 error) *MockTrustPruner_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrustPruner_Execute_Call) RunAndReturn(run func(string) (int, error)) *MockTrustPruner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrustPruner creates a new instance of MockTrustPruner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrustPruner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrustPruner {
	mock := &MockTrustPruner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
