// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Info provides a mock function with given fields: format, args
func (_m *MockLogger) Info(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Info(format interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(format string, args ...interface{})) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Success provides a mock function with given fields: format, args
func (_m *MockLogger) Success(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Success_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Success'
type MockLogger_Success_Call struct {
	*mock.Call
}

// Success is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Success(format interface{}, args ...interface{}) *MockLogger_Success_Call {
	return &MockLogger_Success_Call{Call: _e.mock.On("Success",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Success_Call) Run(run func(format string, args ...interface{})) *MockLogger_Success_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Success_Call) Return() *MockLogger_Success_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Success_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Success_Call {
	_c.Run(run)
	return _c
}

// Verbose provides a mock function with given fields: format, args
func (_m *MockLogger) Verbose(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Verbose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verbose'
type MockLogger_Verbose_Call struct {
	*mock.Call
}

// Verbose is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Verbose(format interface{}, args ...interface{}) *MockLogger_Verbose_Call {
	return &MockLogger_Verbose_Call{Call: _e.mock.On("Verbose",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Verbose_Call) Run(run func(format string, args ...interface{})) *MockLogger_Verbose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Verbose_Call) Return() *MockLogger_Verbose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Verbose_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Verbose_Call {
	_c.Run(run)
	return _c
}

// Warning provides a mock function with given fields: format, args
func (_m *MockLogger) Warning(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Warning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warning'
type MockLogger_Warning_Call struct {
	*mock.Call
}

// Warning is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Warning(format interface{}, args ...interface{}) *MockLogger_Warning_Call {
	return &MockLogger_Warning_Call{Call: _e.mock.On("Warning",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Warning_Call) Run(run func(format string, args ...interface{})) *MockLogger_Warning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warning_Call) Return() *MockLogger_Warning_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warning_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Warning_Call {
	_c.Run(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
