// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStatePruner is an autogenerated mock type for the StatePruner type
type MockStatePruner struct {
	mock.Mock
}

type MockStatePruner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatePruner) EXPECT() *MockStatePruner_Expecter {
	return &MockStatePruner_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *MockStatePruner) Execute() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatePruner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStatePruner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockStatePruner_Expecter) Execute() *MockStatePruner_Execute_Call {
	return &MockStatePruner_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockStatePruner_Execute_Call) Run(run func()) *MockStatePruner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatePruner_Execute_Call) Return(_a0 int, _a1 error) *MockStatePruner_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatePruner_Execute_Call) RunAndReturn(run func() (int, error)) *MockStatePruner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatePruner creates a new instance of MockStatePruner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatePruner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatePruner {
	mock := &MockStatePruner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
