// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStateChecker is an autogenerated mock type for the StateChecker type
type MockStateChecker struct {
	mock.Mock
}

type MockStateChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateChecker) EXPECT() *MockStateChecker_Expecter {
	return &MockStateChecker_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: path
func (_m *MockStateChecker) Execute(path string) (bool, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStateChecker_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStateChecker_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - path string
func (_e *MockStateChecker_Expecter) Execute(path interface{}) *MockStateChecker_Execute_Call {
	return &MockStateChecker_Execute_Call{Call: _e.mock.On("Execute", path)}
}

func (_c *MockStateChecker_Execute_Call) Run(run func(path string)) *MockStateChecker_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStateChecker_Execute_Call) Return(managed bool, err error) *MockStateChecker_Execute_Call {
	_c.Call.Return(managed, err)
	return _c
}

func (_c *MockStateChecker_Execute_Call) RunAndReturn(run func(string) (bool, error)) *MockStateChecker_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStateChecker creates a new instance of MockStateChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateChecker {
	mock := &MockStateChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
