// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStateAdopter is an autogenerated mock type for the StateAdopter type
type MockStateAdopter struct {
	mock.Mock
}

type MockStateAdopter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateAdopter) EXPECT() *MockStateAdopter_Expecter {
	return &MockStateAdopter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: path, repo, branch
func (_m *MockStateAdopter) Execute(path string, repo string, branch string) error {
	ret := _m.Called(path, repo, branch)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(path, repo, branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStateAdopter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStateAdopter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - path string
//   - repo string
//   - branch string
func (_e *MockStateAdopter_Expecter) Execute(path interface{}, repo interface{}, branch interface{}) *MockStateAdopter_Execute_Call {
	return &MockStateAdopter_Execute_Call{Call: _e.mock.On("Execute", path, repo, branch)}
}

func (_c *MockStateAdopter_Execute_Call) Run(run func(path string, repo string, branch string)) *MockStateAdopter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStateAdopter_Execute_Call) Return(_a0 error) *MockStateAdopter_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStateAdopter_Execute_Call) RunAndReturn(run func(string, string, string) error) *MockStateAdopter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStateAdopter creates a new instance of MockStateAdopter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateAdopter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateAdopter {
	mock := &MockStateAdopter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
