// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	iterm "github.com/joescharf/wt/internal/iterm"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CloseWindow provides a mock function with given fields: sessionID
func (_m *MockClient) CloseWindow(sessionID string) error {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CloseWindow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_CloseWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseWindow'
type MockClient_CloseWindow_Call struct {
	*mock.Call
}

// CloseWindow is a helper method to define mock.On call
//   - sessionID string
func (_e *MockClient_Expecter) CloseWindow(sessionID interface{}) *MockClient_CloseWindow_Call {
	return &MockClient_CloseWindow_Call{Call: _e.mock.On("CloseWindow", sessionID)}
}

func (_c *MockClient_CloseWindow_Call) Run(run func(sessionID string)) *MockClient_CloseWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_CloseWindow_Call) Return(_a0 error) *MockClient_CloseWindow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_CloseWindow_Call) RunAndReturn(run func(string) error) *MockClient_CloseWindow_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorktreeWindow provides a mock function with given fields: path, name, noClaude
func (_m *MockClient) CreateWorktreeWindow(path string, name string, noClaude bool) (*iterm.SessionIDs, error) {
	ret := _m.Called(path, name, noClaude)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorktreeWindow")
	}

	var r0 *iterm.SessionIDs
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool) (*iterm.SessionIDs, error)); ok {
		return rf(path, name, noClaude)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool) *iterm.SessionIDs); ok {
		r0 = rf(path, name, noClaude)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iterm.SessionIDs)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(path, name, noClaude)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateWorktreeWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorktreeWindow'
type MockClient_CreateWorktreeWindow_Call struct {
	*mock.Call
}

// CreateWorktreeWindow is a helper method to define mock.On call
//   - path string
//   - name string
//   - noClaude bool
func (_e *MockClient_Expecter) CreateWorktreeWindow(path interface{}, name interface{}, noClaude interface{}) *MockClient_CreateWorktreeWindow_Call {
	return &MockClient_CreateWorktreeWindow_Call{Call: _e.mock.On("CreateWorktreeWindow", path, name, noClaude)}
}

func (_c *MockClient_CreateWorktreeWindow_Call) Run(run func(path string, name string, noClaude bool)) *MockClient_CreateWorktreeWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockClient_CreateWorktreeWindow_Call) Return(_a0 *iterm.SessionIDs, _a1 error) *MockClient_CreateWorktreeWindow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateWorktreeWindow_Call) RunAndReturn(run func(string, string, bool) (*iterm.SessionIDs, error)) *MockClient_CreateWorktreeWindow_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureRunning provides a mock function with no fields
func (_m *MockClient) EnsureRunning() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnsureRunning")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_EnsureRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureRunning'
type MockClient_EnsureRunning_Call struct {
	*mock.Call
}

// EnsureRunning is a helper method to define mock.On call
func (_e *MockClient_Expecter) EnsureRunning() *MockClient_EnsureRunning_Call {
	return &MockClient_EnsureRunning_Call{Call: _e.mock.On("EnsureRunning")}
}

func (_c *MockClient_EnsureRunning_Call) Run(run func()) *MockClient_EnsureRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_EnsureRunning_Call) Return(_a0 error) *MockClient_EnsureRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_EnsureRunning_Call) RunAndReturn(run func() error) *MockClient_EnsureRunning_Call {
	_c.Call.Return(run)
	return _c
}

// FocusWindow provides a mock function with given fields: sessionID
func (_m *MockClient) FocusWindow(sessionID string) error {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FocusWindow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_FocusWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FocusWindow'
type MockClient_FocusWindow_Call struct {
	*mock.Call
}

// FocusWindow is a helper method to define mock.On call
//   - sessionID string
func (_e *MockClient_Expecter) FocusWindow(sessionID interface{}) *MockClient_FocusWindow_Call {
	return &MockClient_FocusWindow_Call{Call: _e.mock.On("FocusWindow", sessionID)}
}

func (_c *MockClient_FocusWindow_Call) Run(run func(sessionID string)) *MockClient_FocusWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_FocusWindow_Call) Return(_a0 error) *MockClient_FocusWindow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_FocusWindow_Call) RunAndReturn(run func(string) error) *MockClient_FocusWindow_Call {
	_c.Call.Return(run)
	return _c
}

// IsRunning provides a mock function with no fields
func (_m *MockClient) IsRunning() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockClient_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockClient_Expecter) IsRunning() *MockClient_IsRunning_Call {
	return &MockClient_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockClient_IsRunning_Call) Run(run func()) *MockClient_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_IsRunning_Call) Return(_a0 bool) *MockClient_IsRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_IsRunning_Call) RunAndReturn(run func() bool) *MockClient_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// SessionExists provides a mock function with given fields: sessionID
func (_m *MockClient) SessionExists(sessionID string) bool {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for SessionExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_SessionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionExists'
type MockClient_SessionExists_Call struct {
	*mock.Call
}

// SessionExists is a helper method to define mock.On call
//   - sessionID string
func (_e *MockClient_Expecter) SessionExists(sessionID interface{}) *MockClient_SessionExists_Call {
	return &MockClient_SessionExists_Call{Call: _e.mock.On("SessionExists", sessionID)}
}

func (_c *MockClient_SessionExists_Call) Run(run func(sessionID string)) *MockClient_SessionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_SessionExists_Call) Return(_a0 bool) *MockClient_SessionExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SessionExists_Call) RunAndReturn(run func(string) bool) *MockClient_SessionExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
